# 1. NUMPY BASICS

In [2]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
my_list=[10,20,50,60,70]
my_list

[10, 20, 50, 60, 70]

In [3]:
# Let's create a numpy array from the list "my_list"
x=np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [4]:
type(x)

numpy.ndarray

In [5]:
# Multi-dimensional (Matrix definition) 
metrics=np.array([[5,8],[9,13]])
metrics

array([[ 5,  8],
       [ 9, 13]])

In [6]:
type(metrics)

numpy.ndarray

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [7]:
my_array=np.array([[4,6,8,7],[20,5,6,9]])
my_array

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [8]:
# "rand()" uniform distribution between 0 and 1
np.random.rand(15)

array([0.24375551, 0.16247174, 0.09712204, 0.32023837, 0.99082868,
       0.00939018, 0.44971135, 0.3960207 , 0.05809608, 0.38258987,
       0.36710188, 0.59993331, 0.49948872, 0.88368864, 0.74585169])

In [9]:
# you can create a matrix of random number as well
x=np.random.rand(5,5)
x

array([[0.25064118, 0.78411632, 0.52809369, 0.48441023, 0.65851823],
       [0.45363855, 0.06671393, 0.93469057, 0.3932862 , 0.53149356],
       [0.21405569, 0.39525057, 0.61962895, 0.67577998, 0.70448037],
       [0.15397259, 0.72299476, 0.58528733, 0.86265839, 0.55775292],
       [0.69733309, 0.3597381 , 0.39397436, 0.80646565, 0.27487562]])

In [10]:
# "randn()" normal distribution between 0 and 1
x=np.random.randn(10)
x

array([-0.40525338, -1.37848887,  0.21247246, -0.25003443,  0.62630907,
       -1.40367399,  0.92895306,  0.58272594,  1.03179499, -1.02097716])

In [11]:
# "randint" is used to generate random integers between upper and lower bounds
x=np.random.randint(1,10)
x

1

In [12]:
# "randint" can be used to generate a certain number of random itegers as follows
z=np.random.randint(1,100,15)
z

array([57, 87, 71, 28, 88, 25, 22, 32, 13, 25, 77, 89, 75, 42,  1])

In [13]:
# np.arange creates an evenly spaced values within a given interval
x=np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [14]:
# Create an evenly spaced values with a step of 5
x=np.arange(1,50,5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [15]:
# create a diagonal of ones and zeros everywhere else
x=np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [16]:
# Array of ones
x=np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
# Matrices of ones
x=np.ones((15,15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [18]:
# Array of zeros
x=np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [19]:
num=int(input("Enter the number:"))
x=np.random.randint(1,num,20)
x

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [55]:
# Let's define a one-dimensional array 
my_list=[-30,4,50,60,29,15,22,90]
my_list
x=np.array(my_list)
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [56]:
# Get Length of a numpy array
len(x)

8

In [57]:
# Get shape
x.shape

(8,)

In [58]:
# Obtain the datatype
x.dtype

dtype('int32')

In [59]:
# Reshape 1D array into a matrix
z=x.reshape(2,4)
z

array([[-30,   4,  50,  60],
       [ 29,  15,  22,  90]])

In [60]:
# Obtain the maximum element (value)
x.max()

90

In [61]:
# Obtain the minimum element (value)
x.min()

-30

In [62]:
# Obtain the location of the max element
x.argmax()

7

In [64]:
# Obtain the location of the min element
x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [66]:
x=np.arange(300,500,10)
x

array([300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420,
       430, 440, 450, 460, 470, 480, 490])

In [67]:
x.shape

(20,)

In [69]:
x=x.reshape(4,5)
x

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [71]:
x=np.random.randint(-1000,1000,(20,20))
x

array([[-478,  765,  935,  693,  936, -714, -139, -107,  -27,  189, -864,
        -223, -277, -234,  589, -283,  430, -732,  420,  221],
       [ 496,  945,  -63,  649,   28, -318, -877, -562, -183, -105,  263,
        -486, -442,  126, -487, -794, -802,   27,   18, -755],
       [ 684,  847,  864, -589,  347, -780, -401, -498, -911,  978,  256,
         466, -283,  255, -306,  361, -410,  451,  624,  218],
       [-759,  869, -205,  853, -531,   96,  962,  891, -470,  729,  164,
         100, -207,   13, -235,  391, -709,  731,  990, -411],
       [-432,  273,  392,  359,    8, -640,    5,  229,  270, -685,   24,
         584, -729,  339,   26, -407,   49, -314, -893, -177],
       [-587,  -48, -706,   10,  -36, -546,  873, -525,  865,  813,  775,
        -790,   12, -738, -211, -707, -369,   42,  773,  600],
       [-316, -853,   19,  355, -468,  -30, -232,  208,  882,  597,  -21,
         669, -487,  594, -113,  249,  -67,  149, -935,  613],
       [-173,   -3, -708,  995, -467,  16

In [72]:
x.shape

(20, 20)

In [73]:
x.max()

995

In [75]:
x.min()

-990

In [76]:
x.mean()

-21.71

# 4. MATHEMATICAL OPERATIONS

In [77]:
# np.arange() returns an evenly spaced values within a given interval
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
y=np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
# Add 2 numpy arrays together
sum=x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [81]:
squered=x**2
squered

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [82]:
sqrt=np.sqrt(squered)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [83]:
z=np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [85]:
x=np.array([3,20,30])
y=np.array([4,6,7])
z=np.sqrt(x**2 + y**2)
z

array([ 5.        , 20.88061302, 30.8058436 ])

# 5. SLICING AND INDEXING 

In [86]:
x=np.array([20,40,50,21,15])
x

array([20, 40, 50, 21, 15])

In [87]:
# Access specific index from the numpy array
x[0]

20

In [89]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[0:3]

array([20, 40, 50])

In [90]:
# Broadcasting, altering several values in a numpy array at once
x[0:2]=10
x

array([10, 10, 50, 21, 15])

In [93]:
# Let's define a two dimensional numpy array
matrix=np.random.randint(1,10,(5,5))
matrix

array([[2, 7, 4, 8, 2],
       [3, 9, 8, 1, 7],
       [7, 5, 6, 5, 2],
       [3, 9, 4, 6, 1],
       [8, 5, 9, 3, 2]])

In [94]:
# Get a row from a mtrix
matrix[2]

array([7, 5, 6, 5, 2])

In [95]:
# Get one element
matrix[0][2]

4

In [96]:
mini_matrix=matrix[:3]
mini_matrix

array([[2, 7, 4, 8, 2],
       [3, 9, 8, 1, 7],
       [7, 5, 6, 5, 2]])

In [99]:
mini_matrix=matrix[2:3,2:]
mini_matrix

array([[6, 5, 2]])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [111]:
x=np.random.randint(-10,50,(5,5))
x

array([[  1,   6,  32,  23,  47],
       [ 18,  -7,  37,  47,  21],
       [ 19,  19,  47,  37,  15],
       [  6,  44,  31,  38,  12],
       [ -7,  24,  31,  11, -10]])

In [112]:
x[4:5]=-1
x

array([[ 1,  6, 32, 23, 47],
       [18, -7, 37, 47, 21],
       [19, 19, 47, 37, 15],
       [ 6, 44, 31, 38, 12],
       [-1, -1, -1, -1, -1]])

In [115]:
z=x[:2,3:]
z

array([[23, 47],
       [47, 21]])

In [116]:
z**2

array([[ 529, 2209],
       [2209,  441]])

# 6. ELEMENTS SELECTION (CONDITIONAL)

In [117]:
matrix=np.random.randint(1,10,(5,5))
matrix

array([[7, 9, 4, 2, 5],
       [7, 3, 7, 3, 7],
       [9, 1, 2, 7, 3],
       [5, 7, 8, 9, 7],
       [8, 5, 5, 3, 2]])

In [118]:
new_matrix=matrix[matrix>3]
new_matrix

array([7, 9, 4, 5, 7, 7, 7, 9, 7, 5, 7, 8, 9, 7, 8, 5, 5])

In [119]:
new_matrix=matrix[matrix%2==0]
new_matrix

array([4, 2, 2, 8, 8, 2])

In [121]:
new_matrix=matrix[matrix%2==1]
new_matrix

array([7, 9, 5, 7, 3, 7, 3, 7, 9, 1, 7, 3, 5, 7, 9, 7, 5, 5, 3])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [123]:
x=np.random.randint(-5,100,(5,5))
x

array([[30, 42, 77,  7, 39],
       [65, 69,  5, 83, 58],
       [36, 55, 23, 48, -2],
       [74, 14, -3, 52, 57],
       [28, 20, 39, 84, 13]])

In [127]:
x[x%2==1]=25
x

array([[30, 42, 25, 25, 25],
       [25, 25, 25, 25, 58],
       [36, 25, 25, 48, -2],
       [74, 14, 25, 52, 25],
       [28, 20, 25, 84, 25]])

In [128]:
x[x<0]=0
x

array([[30, 42, 25, 25, 25],
       [25, 25, 25, 25, 58],
       [36, 25, 25, 48,  0],
       [74, 14, 25, 52, 25],
       [28, 20, 25, 84, 25]])

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [37]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

array([[[ 4,  6,  8,  7],
        [20,  5,  6,  9]]])

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [38]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

array([1, 3, 1, 3, 3, 2, 1, 2, 1, 2, 2, 2, 1, 3, 1, 2, 3, 1, 3, 2])

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [39]:
x = np.arange(300, 500, 10)
x.shape

(20,)

In [40]:
x = x.reshape(4, 5)
print(x)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [41]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[-381  594 -793 -448  677 -248  780  971 -752  878 -167 -696 -481 -868
   614  -31   95  -88  176 -689]
 [-477  516   12  745   32  961  243  686 -806  478 -962 -472 -372 -204
  -881  716  513 -913 -245 -743]
 [ 665  263  260  158   94 -686 -411 -323  -97 -553 -875 -541  187  -73
   318 -954  325  606  742 -719]
 [ -39  507 -437 -499 -284 -716 -441 -865  868  345  -16  601 -839 -565
   462 -515  290 -610  -96 -637]
 [ -66  723 -402  505 -261  762  799 -351  141 -531  377  565  716  856
   766  652 -716 -130  430 -741]
 [-828  455  550 -358 -669 -469  750  687  792 -320  128 -179 -910 -624
  -705 -220 -965  737 -443  -82]
 [-248 -813 -809 -975  674  550  187  647  898 -393 -923  -11  -78 -517
   798  -33 -551  600 -522  689]
 [-638  581 -240 -447 -383  168 -989  392  504 -390 -702  438 -495  968
  -969  -57 -266  384 -187 -372]
 [ 536 -363  482  131  570  148  189  -84  792  581 -704 -512 -912 -299
   860  990 -642  252  -25 -131]
 [ 535  847 -740 -912  187  622 -105 -872 -739  625  -9

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [42]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [43]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [44]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [45]:
X[:2, 3:]  = X[:2, 3:] * 2

In [46]:
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [47]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40, 25,  0],
       [25,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])